language: node_js
sudo: false
node_js:
- '5'
branches:
  only:
  - /^v[0-9]/
after_success:
- npm run build
deploy:
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: sgPs40UBTfMYwSJyOceG/I/ZCKwqr7ZeWsIbWHqHX6T9tBDXGm03ySxRmiTziCJgwrAjDkApNThAZuhiT36oCFB2nfJUXpeRB6xjbevK1lqejqUofR7QKO4mKgmfMlMLS2S8nIWMD2E0bXIG1p/IzWtvtSnVLLBXMRmlvSHI1USGDLoVUVXFd0cAqQ58Td+99Mmkb0bNtetFjkxf44e4NLdVi06wliWgFqi5ZibpikbuDd3QA4YrLBTX0pAcmcr3CHU3MxBQvguCzjpZTkmN1uZ1jOQTUIWMDDDUiAe3ZHwA015XMfdUEZcBfeT/izQZIK2uYuf9vB8Vb1yrucUOG+E3IINqkzEv/QX6yK+0Uz970e1g5BF2yBUVrMOfK8OTBWq815qks+SRrMCYi+Zn57/tkxIge8Pjb23ZEnIi/qLNiAm3QDbR9nTcqMdh6SWuolh7zh5FGKofiM+PF7wm4GQR6dFgHRaryZDa67ealMNq0PESnK2uli3OayJ5xsYxs6Q7XfeCU8vIvoa9+0U9vHbyAhXDlaRwnx03fVAk343wySaTuBFPnpDGWut3Wi9Ewg0rAec1sIg1xnjYAcbQZf/wInqYAb3iPTQV3+vb9P64eEBUK+JAANBIxgEnhUVIOfLIstKzP11G/NcjmY92Yp6mi0QiXQkjP92zJJn0qzM=
  bucket: connector-factory-static.octoblu.com
  local_dir: dist
  skip_cleanup: true
  region: us-west-2
  on:
    tags: true
